/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 syndra.glb --types 
Author: Wilson (https://sketchfab.com/neilhancart)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/syndra-fe72ce65d8ee464da3de9e4825cbc922
Title: Syndra
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    UCX_StaticMeshActor_4_lambert1_0: THREE.Mesh
    UCX_StaticMeshActor_5_lambert1_0: THREE.Mesh
    SkeletalMeshComponent0_Clothes_Inst1_0: THREE.Mesh
    SkeletalMeshComponent0_aiStandardSurface5_Inst1_0: THREE.Mesh
    SkeletalMeshComponent0_Acc_mat_Inst1_0: THREE.Mesh
    SkeletalMeshComponent0_CHAIN_Inst1_0: THREE.Mesh
    SkeletalMeshComponent0_Fbx_Default_Material_6_0: THREE.Mesh
    SkeletalMeshComponent0_Fbx_Default_Material_7_0: THREE.Mesh
    SkeletalMeshComponent0_Body1_Inst1_0: THREE.Mesh
    UCX_StaticMeshActor_3_lambert1_0: THREE.Mesh
  }
  materials: {
    lambert1: THREE.MeshPhysicalMaterial
    Clothes_Inst1: THREE.MeshStandardMaterial
    aiStandardSurface5_Inst1: THREE.MeshStandardMaterial
    Acc_mat_Inst1: THREE.MeshStandardMaterial
    CHAIN_Inst1: THREE.MeshStandardMaterial
    Fbx_Default_Material_6: THREE.MeshStandardMaterial
    Fbx_Default_Material_7: THREE.MeshStandardMaterial
    Body1_Inst1: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/syndra.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-10.179, 0, -5.386]}>
          <group position={[42.051, 0, -757.87]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
            <mesh geometry={nodes.SkeletalMeshComponent0_Clothes_Inst1_0.geometry} material={materials.Clothes_Inst1} />
            <mesh geometry={nodes.SkeletalMeshComponent0_aiStandardSurface5_Inst1_0.geometry} material={materials.aiStandardSurface5_Inst1} />
            <mesh geometry={nodes.SkeletalMeshComponent0_Acc_mat_Inst1_0.geometry} material={materials.Acc_mat_Inst1} />
            <mesh geometry={nodes.SkeletalMeshComponent0_CHAIN_Inst1_0.geometry} material={materials.CHAIN_Inst1} />
            <mesh geometry={nodes.SkeletalMeshComponent0_Fbx_Default_Material_6_0.geometry} material={materials.Fbx_Default_Material_6} />
            <mesh geometry={nodes.SkeletalMeshComponent0_Fbx_Default_Material_7_0.geometry} material={materials.Fbx_Default_Material_7} />
            <mesh geometry={nodes.SkeletalMeshComponent0_Body1_Inst1_0.geometry} material={materials.Body1_Inst1} />
          </group>
          <mesh geometry={nodes.UCX_StaticMeshActor_4_lambert1_0.geometry} material={materials.lambert1} position={[13.385, 8.723, -71.449]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.188} />
          <mesh geometry={nodes.UCX_StaticMeshActor_5_lambert1_0.geometry} material={materials.lambert1} position={[99.334, 59.371, 8.308]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.188} />
          <mesh geometry={nodes.UCX_StaticMeshActor_3_lambert1_0.geometry} material={materials.lambert1} position={[-13.105, -8.27, 64.046]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.188} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/syndra.glb')
